### ISSUE TITLE
Package-based routing and scalability

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#108]
We need a way of segmenting packaged functionality by VM for enhanced scalability and rollout control.  Our mechanism for grouping features together is already well established in our asset packages concept.  To avoid forcing separate Git repositories for each package group, we already have in mind the notion of a yaml configuration file that governs which packages from a repo are applicable for a particular environment.

We need an approach that builds on this and the routing strategy concept to automatically route REST requests based on resource path to a server instance that has the appropriate packages configured.  We can consider adding the configured package info in the AppSummary response so that the routing instance can know about this relationship for each node.  Also, we no longer want to require a dedicated routing instance.  In fact, each instance should be intelligent enough to route to it's peers.

**Comment by donaldoakes** [comment]
Sample mdw.yml:
```yaml
endpoints:
  discovery:
    - https://mdw.useast.appfog.ctl.io/mdw
    - http://lxdenvmtc143.dev.qintra.com:7021/Discovery
  releases:
    - http://repo.maven.apache.org/maven2
  
# optional section for package groups
  packageGroups:
    base:
      routes:
        - /
      packages:
        - com.centurylink.mdw.base
        - com.centurylink.mdw.camel
        - com.centurylink.mdw.db
        - com.centurylink.mdw.hub
    demo-workflow:
      routes:
        - /services/intro
      packages: 
        - com.centurylink.mdw.demo.cool
        - com.centurylink.mdw.demo.intro
    demo-services:
      routes:
        - /services/bugs
      packages:
        - /bugs
      
# optional section for remote projects (replaces plugin.xml)
  mdw.version: 6.0.04-SNAPSHOT
  server:
    host: localhost
    port: 8080
    context: mdw
```
